---
- name: Install benchmark and dependencies
  hosts: localhost
  tasks:
    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes

    - name: Install dependencies
      become: yes
      apt:
        name:
          - bc
          - g++
          - numactl
        state: present

    - name: Install dependencies
      command: g++ latency.cpp -o latency -O3 -march=native
      args:
        chdir: /home/ubuntu/cache_latency


    - name: Make run_latency.sh executable
      file:
        path: /home/ubuntu/cache_latency/run_latency.sh
        mode: '0755'
