---
- name: Install fio and dependencies
  hosts: localhost
  tasks:
    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes

    - name: Install dependencies
      become: yes
      apt:
        name:
          - fio
        state: present

    - name: Make run_fio.sh executable
      file:
        path: ~/fio/run_fio.sh
        mode: '0755'

    - name: Make SSD readeable and writable
      become: yes
      file:
        path: /dev/nvme0n1
        mode: '0666'
