---
configuration:
    name: "FIO"
    description: "Flexible I/O - benchmark for SSD"
    directory: memory_bandwidth
    cron: "0 * * * *"
    instance-number: 1
    instance-types:
      - c5ad.large
nodes:
  - node-id: 0
    ansible-configuration: ansible.yml
    benchmark-command: ./run_fio.sh
    output-command: python3 format_output.py

plots:
  - type: line
    title: CPU Benchmark - Events per second
    xaxis: Threads number
    yaxis: Events per second
    data:
      - x: threads_0
        y: events_per_sec_0
        legend: Instance 1

