---
- name: Compile C++ Server Program
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install g++
      become: true
      package:
        name: g++
        state: present

    - name: Compile server.cpp
      shell: g++ -o server server.cpp

    - name: Confirm compilation success
      stat:
        path: ~/test_bench/server
      register: server_compiled

    - name: Print compilation status
      debug:
        msg: "Server compilation {{ 'succeeded' if server_compiled.stat.exists else 'failed' }}."

